"""add measurement sessions

Revision ID: 3d3c3e251db3
Revises: a7207068a450
Create Date: 2026-10-06 16:53:23.354396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3c3e251db3'
down_revision: Union[str, Sequence[str], None] = 'a7207068a450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='sessionstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_sessions_device_id'), 'measurement_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_measurement_sessions_user_id'), 'measurement_sessions', ['user_id'], unique=False)
    op.add_column('sensor_readings', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sensor_readings_session_id'), 'sensor_readings', ['session_id'], unique=False)
    op.create_foreign_key(None, 'sensor_readings', 'measurement_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'sensor_readings', type_='foreignkey')
    op.drop_index(op.f('ix_sensor_readings_session_id'), table_name='sensor_readings')
    op.drop_column('sensor_readings', 'session_id')
    op.drop_index(op.f('ix_measurement_sessions_user_id'), table_name='measurement_sessions')
    op.drop_index(op.f('ix_measurement_sessions_device_id'), table_name='measurement_sessions')
    op.drop_table('measurement_sessions')
    # ### end Alembic commands ###
